# Generated by Django 5.2.5 on 2025-09-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickup_consumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickuptask',
            name='registro',
            field=models.DateField(blank=True, null=True, verbose_name='Registro'),
        ),
    ]
