# Generated by Django 5.2.5 on 2025-09-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickup_consumer', '0002_clickuptask_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clickuptask',
            name='registro',
        ),
    ]
