# Generated by Django 5.2.5 on 2025-09-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickup_consumer', '0003_remove_clickuptask_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickuptask',
            old_name='cor_prioridade',
            new_name='Cor_Prioridade',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='criado_por',
            new_name='Criado_por',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='data_done',
            new_name='Data_Done',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='data_fechamento',
            new_name='Data_Fechamento',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='data_de_termino_real',
            new_name='Data_de_termino_real',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='espaco',
            new_name='Espaço',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='clickup_id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='lista_origem',
            new_name='List_Origem',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='nome_da_entrega',
            new_name='Nome_da_Entrega',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='prazo',
            new_name='Prazo',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='prioridade',
            new_name='Prioridade',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='responsavel',
            new_name='Responsavel',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='tags',
            new_name='Tags',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='task_nome',
            new_name='Task_Nome',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='arquivado',
            new_name='arquived',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='data_atualizacao',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='nivel_permissao',
            new_name='permission_level',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='id_equipe',
            new_name='team_id',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='tempo_estimado',
            new_name='time_estimate',
        ),
        migrations.RemoveField(
            model_name='clickuptask',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='clickuptask',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='clickuptask',
            name='Data_Criacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Criação'),
        ),
    ]
