# Generated by Django 5.2.5 on 2025-09-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickup_consumer', '0004_rename_cor_prioridade_clickuptask_cor_prioridade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickuptask',
            old_name='arquived',
            new_name='arquivado',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='ID',
            new_name='clickup_id',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='Cor_Prioridade',
            new_name='cor_prioridade',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='Criado_por',
            new_name='criado_por',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='Data_Criacao',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='Data_de_termino_real',
            new_name='data_de_termino_real',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='Data_Done',
            new_name='data_done',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='Data_Fechamento',
            new_name='data_fechamento',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='Espaço',
            new_name='espaco',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='team_id',
            new_name='id_equipe',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='List_Origem',
            new_name='lista_origem',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='permission_level',
            new_name='nivel_permissao',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='Nome_da_Entrega',
            new_name='nome_da_entrega',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='Prazo',
            new_name='prazo',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='Prioridade',
            new_name='prioridade',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='Responsavel',
            new_name='responsavel',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='Tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='Task_Nome',
            new_name='task_nome',
        ),
        migrations.RenameField(
            model_name='clickuptask',
            old_name='time_estimate',
            new_name='tempo_estimado',
        ),
        migrations.RemoveField(
            model_name='clickuptask',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='clickuptask',
            name='data_atualizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='clickuptask',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
    ]
