# Generated by Django 5.2.5 on 2025-09-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickup_consumer', '0005_rename_arquived_clickuptask_arquivado_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clickuptask',
            table='clickup_consumer_clickuptask',
        ),
    ]
